# Generated by Django 5.2.1 on 2025-06-06 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SaborDaComida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cardapio',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, verbose_name='nome do prato')),
                ('data_criacao', models.DateField()),
                ('data_ingresso_menu', models.DateField()),
                ('epoca', models.CharField(choices=[('V', 'Verão'), ('O', 'Outono'), ('I', 'Inverno'), ('P', 'Primavera')], max_length=2, verbose_name='epoca da comida')),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.ingrediente')),
                ('saborDaComida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.sabordacomida', verbose_name='sabor da comida')),
            ],
        ),
    ]
